# Generated by Django 6.0.5 on 2026-05-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR code'), ('card', 'Card'), ('bank', 'Bank transfer'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
